export default function Docs() {
  return (
    <div style={{ animation: 'fadeUp 0.3s ease', maxWidth: 860 }}>
      <div className="page-header">
        <div>
          <div className="page-title">System Docs</div>
          <div className="page-subtitle">How the whole system works — read this to understand everything</div>
        </div>
      </div>

      <Section title="Architecture Overview">
        <p>This is an <strong>event-sourced personal finance tracker</strong>. Everything is built around a single principle:</p>
        <Callout color="indigo">Discord is the permanent ledger. MySQL is just a derived cache. If the database is wiped, Sync rebuilds it 100% from Discord history.</Callout>
        <p>The flow is:</p>
        <Code>{`You (App UI or Discord) → POST /api/events → event_engine.py → MySQL state update → React Dashboard`}</Code>
        <p>Every financial action — creating an account, recording an expense, making a transfer — is posted as a JSON event. The engine processes it and updates the database. The React frontend reads from the database.</p>
      </Section>

      <Section title="Transaction Types">
        <p>Transactions are the core records. Every movement of money is a transaction. There are three <strong>types</strong>:</p>
        <Table
          headers={['Type', 'Effect on Balance', 'When to use']}
          rows={[
            ['income',   '+  adds to balance',    'You received money'],
            ['expense',  '−  deducts from balance','You spent money'],
            ['transfer', '−  deducts from balance','Auto-generated by the Transfer system — do not create manually'],
          ]}
        />
        <p>Transactions also have an optional <strong>sub_type</strong> that gives more meaning:</p>
        <Table
          headers={['Sub Type', 'Parent Type', 'Meaning']}
          rows={[
            ['(none)',   'income',  'Regular earned income — salary, freelance, etc.'],
            ['initial', 'income',  'Money you already had before you started tracking. Adds to balance but not counted as "earned".'],
            ['borrow',  'income',  'Someone lent you money. Adds to balance but you owe it back. Use Note to record who lent it to you.'],
            ['(none)',   'expense', 'Regular cash/card expense — food, transport, bills.'],
            ['sent_to', 'expense', 'You sent money to a specific person or external service (e.g. paid rent via bKash to landlord). Records the recipient name.'],
            ['lent',    'expense', 'You lent money to someone. Decreases your balance. They owe you back. Use Note to record who you lent it to.'],
          ]}
        />
        <Callout color="amber">The <code>transfer</code> type is auto-generated internally when you create a Transfer. You cannot create it manually from the UI. Use the Transfers page instead.</Callout>
      </Section>

      <Section title="Transfers">
        <p>A Transfer moves money between <strong>two of your own accounts</strong>. It automatically creates two transactions:</p>
        <ul>
          <li>A <strong>debit</strong> (type: transfer) on the sending account — deducts <code>from_amount + charge</code></li>
          <li>A <strong>credit</strong> (type: income) on the receiving account — adds <code>to_amount</code></li>
        </ul>
        <p>This supports:</p>
        <Table
          headers={['Scenario', 'Example']}
          rows={[
            ['Same currency, no charge',      'Wallet → Bkash: send 500 BDT, receive 500 BDT, charge 0'],
            ['Same currency, with charge',    'Wallet → Bkash: send 1000 BDT, charge 30 BDT, receive 970 BDT — sender pays 1030 total'],
            ['Cross-currency',                'Bank → USD account: send 1000 BDT, receive 9.20 USD — you enter the received amount manually'],
            ['Cross-currency with charge',    'Bkash → USD: send 1000 BDT + 20 BDT fee, receive 9.00 USD'],
          ]}
        />
        <Callout color="red">Deleting a Transfer soft-deletes both the debit and credit transactions. The money is reversed in both accounts.</Callout>
        <p><strong>Transfer ≠ Expense sent to someone.</strong> If you sent money to an external person (your landlord, a shop), that is an <em>Expense</em> with <code>sub_type: sent_to</code> — not a Transfer. Transfers are only between accounts you own inside this system.</p>
      </Section>

      <Section title="Accounts">
        <p>Accounts represent your money containers. Each account has a type:</p>
        <Table
          headers={['Type', 'Use for']}
          rows={[
            ['cash',   'Physical wallet / cash in hand'],
            ['bank',   'Bank account (EBL, DBBL, Dutch-Bangla, etc.)'],
            ['card',   'Credit or debit card'],
            ['bkash',  'bKash mobile banking'],
            ['nagad',  'Nagad mobile banking'],
            ['rocket', 'Rocket (DBBL) mobile banking'],
            ['upay',   'uPay mobile banking'],
            ['tap',    'Tap digital wallet'],
          ]}
        />
        <p>Account balance is calculated live from all non-deleted transactions linked to that account:</p>
        <Code>Balance = SUM(income transactions) − SUM(expense + transfer transactions)</Code>
        <p>Deleting an account soft-deletes it — it disappears from the UI but the event stays in the ledger. Transactions linked to a deleted account are still in the database.</p>
      </Section>

      <Section title="Balance Calculation">
        <p>All balance calculations follow one rule:</p>
        <Code>{`income (including initial + borrow) → +\nexpense (including sent_to) → −\ntransfer (auto-generated debit) → −`}</Code>
        <p>This means:</p>
        <ul>
          <li><strong>Initial balance</strong> adds to your balance (it's typed as income)</li>
          <li><strong>Borrowed money</strong> adds to your balance (it's typed as income) — tracked separately so you know you owe it back</li>
          <li><strong>Lent money</strong> deducts from your balance (it's typed as expense) — tracked separately so you know someone owes you</li>
          <li><strong>Sent to someone</strong> deducts from balance (it's typed as expense)</li>
          <li>When you do a Transfer, the sender account loses <code>from_amount + charge</code> and the receiver gains <code>to_amount</code></li>
        </ul>
        <Callout color="indigo">The system prevents overspending. If an expense or transfer amount exceeds the account's current balance, it will be rejected with an error.</Callout>
      </Section>

      <Section title="Event System">
        <p>Every action is an <strong>event</strong>. Events have this structure:</p>
        <Code>{`{
  "event_id": "unique-uuid",       // Must be unique — prevents duplicate processing
  "action": "insert|update|delete",
  "entity": "transaction|account|transfer",
  "target_id": "id-of-existing-record",  // Required for update/delete
  "data": { ... },                 // Entity-specific fields
  "source": "app|discord"          // Set automatically
}`}</Code>
        <p><strong>Idempotency:</strong> If the same <code>event_id</code> is processed twice, the second one is silently ignored. This means it is always safe to re-sync — duplicate events will never corrupt your data.</p>
        <p><strong>Soft deletes:</strong> Deleting a transaction or account never removes the database row. It sets <code>deleted_at</code> to the current time. You can view and restore deleted transactions from the Deleted page.</p>
      </Section>

      <Section title="Discord Sync">
        <p>The <strong>Sync Discord</strong> button on the Dashboard does a full rebuild:</p>
        <ol>
          <li>Fetches every message from your Discord finance channel</li>
          <li>Wipes the accounts, transactions, transfers, and events tables</li>
          <li>Replays every valid JSON event in chronological order</li>
        </ol>
        <p>All messages — whether posted by you or the Finance Bot — are scanned. Any message that is valid JSON with <code>event_id</code> and <code>action</code> keys is treated as an event.</p>
        <Callout color="amber">Any change you make through the app UI is <strong>automatically mirrored to Discord</strong> by the bot. This is why your data survives a sync — the bot already wrote it to the ledger.</Callout>
      </Section>

      <Section title="Pages Reference">
        <Table
          headers={['Page', 'What it does', 'Requires']}
          rows={[
            ['Dashboard',      'Summary cards (income/expense/balance per currency), 14-day chart, recent transactions, sync button', 'Accounts + Transactions'],
            ['Transactions',   'Create, view, edit, delete income and expense transactions. Shows sub_type badges (initial, borrowed, sent to).', 'At least one account'],
            ['Transfers',      'Create transfers between your own accounts with optional charge and cross-currency support.', 'At least two accounts'],
            ['Accounts',       'Create, edit, delete accounts. View per-account balance.', '—'],
            ['Analytics',      'Income vs expense bar chart (last 30 days), expense breakdown by category pie chart.', 'Transactions'],
            ['Convert',        'Live currency conversion tool. Fetches real exchange rates.', 'Internet'],
            ['Deleted',        'View soft-deleted transactions. Restore them with one click.', '—'],
            ['Discord Schema', 'Generate JSON templates for every event type. Copy to paste into Discord.', '—'],
            ['Docs (this page)', 'System documentation.', '—'],
          ]}
        />
      </Section>

      <Section title="Edge Cases & Rules">
        <ul style={{ lineHeight: 2 }}>
          <li><strong>Transfer to yourself blocked:</strong> You cannot create a transfer where from and to are the same account.</li>
          <li><strong>Overspend blocked:</strong> Expense or Transfer that exceeds account balance is rejected.</li>
          <li><strong>Initial balance is income:</strong> For balance math, initial balance counts as income. It just has a different label.</li>
          <li><strong>Borrowed money is income:</strong> It increases your balance. Track who you owe in the Note field.</li>
          <li><strong>Auto-transfer transactions are locked:</strong> Transfer-type transactions generated by the Transfer system cannot be edited manually. Delete the Transfer record instead.</li>
          <li><strong>Cross-currency balance:</strong> Each currency's balance is tracked separately. Dashboard shows one summary block per currency.</li>
          <li><strong>Charge is paid by sender:</strong> In a transfer, the charge is deducted from the sending account on top of the send amount. The receiver always gets exactly <code>to_amount</code>.</li>
          <li><strong>Year-End Reset:</strong> Shows a preview of what carries forward (account balances, open borrows, open lents), posts them as new events to Discord, then wipes all history. Zero-balance accounts are skipped. Irreversible — confirm carefully.</li>
          <li><strong>Carryforward safety:</strong> If posting to Discord fails for any event, the reset is aborted entirely — no data is lost. Fix the Discord connection and retry.</li>
        </ul>
      </Section>
    </div>
  )
}

// --- Internal layout helpers ---

function Section({ title, children }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <div style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 14, paddingBottom: 8, borderBottom: '2px solid var(--border)' }}>{title}</div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, color: 'var(--text-secondary)', fontSize: 14, lineHeight: 1.7 }}>{children}</div>
    </div>
  )
}

function Callout({ color, children }) {
  const colors = {
    indigo: { bg: 'rgba(99,102,241,0.08)',  border: 'rgba(99,102,241,0.3)',  text: '#818cf8' },
    amber:  { bg: 'rgba(245,158,11,0.08)',  border: 'rgba(245,158,11,0.3)',  text: '#f59e0b' },
    red:    { bg: 'rgba(239,68,68,0.08)',   border: 'rgba(239,68,68,0.3)',   text: '#f87171' },
  }
  const c = colors[color] || colors.indigo
  return (
    <div style={{ background: c.bg, border: `1px solid ${c.border}`, borderRadius: 8, padding: '10px 14px', color: c.text, fontSize: 13 }}>
      {children}
    </div>
  )
}

function Code({ children }) {
  return (
    <pre style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)', borderRadius: 8, padding: '10px 14px', fontFamily: 'monospace', fontSize: 13, color: 'var(--text-primary)', overflowX: 'auto', whiteSpace: 'pre-wrap' }}>
      {children}
    </pre>
  )
}

function Table({ headers, rows }) {
  return (
    <div style={{ overflowX: 'auto' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
        <thead>
          <tr>
            {headers.map(h => (
              <th key={h} style={{ textAlign: 'left', padding: '8px 12px', background: 'var(--bg-surface)', color: 'var(--text-muted)', fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', borderBottom: '1px solid var(--border)' }}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} style={{ borderBottom: '1px solid var(--border)' }}>
              {row.map((cell, j) => (
                <td key={j} style={{ padding: '9px 12px', color: j === 0 ? 'var(--text-primary)' : 'var(--text-secondary)', fontWeight: j === 0 ? 600 : 400, fontFamily: j === 0 ? 'monospace' : 'inherit', fontSize: j === 0 ? 12 : 13 }}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
